apiVersion: v1
entries:
  mychart:
  - apiVersion: v2
    appVersion: 1.0.0
    created: "2025-03-04T04:32:59.473180291Z"
    dependencies:
    - name: kube-prometheus-stack
      repository: https://prometheus-community.github.io/helm-charts
      version: 55.5.0
    description: A Helm chart for Kubernetes
    digest: eafafc9e0508cca6355c90ebd39fe21668a8cce8e462af321ffa66e6048fded4
    name: mychart
    type: application
    urls:
    - mychart-0.1.0.tgz
    version: 0.1.0
  - apiVersion: v2
    appVersion: 1.0.0
    created: "2025-03-04T04:32:59.507602948Z"
    dependencies:
    - name: kube-prometheus-stack
      repository: https://prometheus-community.github.io/helm-charts
      version: 55.5.0
    description: A Helm chart for Kubernetes
    digest: 12e7ec9edef6b000207fca5010381ea1b80f042bc51a4b7cd68431cc4b202b80
    name: mychart
    type: application
    urls:
    - charts/mychart-0.1.0.tgz
    version: 0.1.0
generated: "2025-03-04T04:32:59.435830863Z"
