apiVersion: v1
entries:
  mychart:
  - apiVersion: v2
    appVersion: 1.0.0
    created: "2025-03-04T03:01:57.448651461Z"
    dependencies:
    - name: kube-prometheus-stack
      repository: https://prometheus-community.github.io/helm-charts
      version: 55.5.0
    description: A Helm chart for Kubernetes
    digest: 4fc87e10b53fd048f8661147acd65c73548b8ac2ece27e05111ef197770ce97e
    name: mychart
    type: application
    urls:
    - mychart-0.1.0.tgz
    version: 0.1.0
  - apiVersion: v2
    appVersion: 1.0.0
    created: "2025-03-04T03:01:57.481709215Z"
    dependencies:
    - name: kube-prometheus-stack
      repository: https://prometheus-community.github.io/helm-charts
      version: 55.5.0
    description: A Helm chart for Kubernetes
    digest: 7ede2c5452d90c157c623ab9a6add2f39daf3b900f0870a49c2a136e8adda1b5
    name: mychart
    type: application
    urls:
    - charts/mychart-0.1.0.tgz
    version: 0.1.0
generated: "2025-03-04T03:01:57.411106662Z"
