apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: ebs-{{ .Values.nameOverride }}
  namespace: {{ .Values.namespaceOverride }}
provisioner: ebs.csi.aws.com
volumeBindingMode: WaitForFirstConsumer
parameters:
  type: gp3
  fsType: ext4
  encrypted: "true"
